metadata:
  creationTimestamp: "2020-02-20T15:44:08Z"
  labels:
    com.docker.default-service-type: ""
    com.docker.deploy-namespace: docker
    com.docker.fry: compose
    com.docker.image-tag: v0.4.23
  name: compose-service
  resourceVersion: "483"
  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterroles/compose-service
  uid: 1aec10e6-909f-47ac-bf04-852bcb6b5fd7
rules:
- apiGroups:
  - ""
  resources:
  - users
  - groups
  - serviceaccounts
  verbs:
  - impersonate
- apiGroups:
  - authentication.k8s.io
  resources:
  - '*'
  verbs:
  - impersonate
- apiGroups:
  - ""
  - apps
  resources:
  - services
  - deployments
  - statefulsets
  - daemonsets
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - compose.docker.com
  resources:
  - stacks
  verbs:
  - '*'
- apiGroups:
  - compose.docker.com
  resources:
  - stacks/owner
  verbs:
  - get
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfigurations
  - mutatingwebhookconfigurations
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - apiregistration.k8s.io
  resourceNames:
  - v1beta1.compose.docker.com
  - v1beta2.compose.docker.com
  - v1alpha3.compose.docker.com
  resources:
  - apiservices
  verbs:
  - '*'
- apiGroups:
  - apiregistration.k8s.io
  resources:
  - apiservices
  verbs:
  - create
