metadata:
  creationTimestamp: "2020-02-20T15:42:49Z"
  name: default
  resourceVersion: "146"
  selfLink: /api/v1/namespaces/default
  uid: d09771eb-81a8-48c8-9232-3d6fb9b6d316
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
