apiVersion: couchbase.com/v2
kind: CouchbaseGroup
metadata:
 name: engineering
spec:
 ldapGroupRef: cn=engineering,ou=groups,dc=wael,dc=couchbase,dc=com
 roles:
 - name: ro_admin
 - name: bucket_full_access
---
apiVersion: couchbase.com/v2
kind: CouchbaseGroup
metadata:
 name: support
spec:
 ldapGroupRef: cn=support,ou=groups,dc=wael,dc=couchbase,dc=com
 roles:
 - name: admin
---
apiVersion: couchbase.com/v2
kind: CouchbaseGroup
metadata:
 name: analytics
spec:
 ldapGroupRef: cn=analytics,ou=groups,dc=wael,dc=couchbase,dc=com
 roles:
 - name: bucket_full_access
