apiVersion: couchbase.com/v2
kind: CouchbaseBucket
metadata:
  creationTimestamp: "2020-04-21T15:56:08Z"
  generation: 1
  labels:
    cluster.couchbase.com: wael
  name: mysql
  namespace: default
  resourceVersion: "2868896"
  selfLink: /apis/couchbase.com/v2/namespaces/default/couchbasebuckets/mysql
  uid: 88e4df7f-ba40-448c-afb5-a20af1125214
spec:
  compressionMode: passive
  conflictResolution: seqno
  evictionPolicy: valueOnly
  ioPriority: low
  memoryQuota: 100Mi
  replicas: 1
