apiVersion: apps/v1
kind: Deployment
metadata:
  name: nifi
  labels:
    app: nifi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nifi
  template:
    metadata:
      labels:
        app: nifi
    spec:
      containers:
      - name: nifi
        image: apache/nifi:1.8.0
        ports:
        - containerPort: 8080
