---
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: couchbase-operator-admission

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: couchbase-operator-admission
rules:
- apiGroups:
  - couchbase.com
  resources:
  - couchbaseclusters
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: couchbase-operator-admission
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: couchbase-operator-admission
subjects:
- kind: ServiceAccount
  name: couchbase-operator-admission
  namespace: cb-eks

---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: couchbase-operator-admission
spec:
  replicas: 1
  selector:
    matchLabels:
      app: couchbase-operator-admission
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: couchbase-operator-admission
    spec:
      containers:
      - args:
        - --logtostderr
        - --stderrthreshold
        - "0"
        - --tls-cert-file
        - /var/run/secrets/couchbase.com/couchbase-operator-admission/tls-cert-file
        - --tls-private-key-file
        - /var/run/secrets/couchbase.com/couchbase-operator-admission/tls-private-key-file
        command:
        - couchbase-operator-admission
        image: couchbase/admission-controller:1.2.2
        name: couchbase-operator-admission
        ports:
        - containerPort: 8443
          name: https
        resources: {}
        volumeMounts:
        - mountPath: /var/run/secrets/couchbase.com/couchbase-operator-admission
          name: couchbase-operator-admission
          readOnly: true
      serviceAccountName: couchbase-operator-admission
      volumes:
      - name: couchbase-operator-admission
        secret:
          secretName: couchbase-operator-admission
status: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: couchbase-operator-admission
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    app: couchbase-operator-admission
status:
  loadBalancer: {}

---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: couchbase-operator-admission
webhooks:
- clientConfig:
    caBundle: Q2VydGlmaWNhdGU6CiAgICBEYXRhOgogICAgICAgIFZlcnNpb246IDMgKDB4MikKICAgICAgICBTZXJpYWwgTnVtYmVyOgogICAgICAgICAgICBmZDpmNDpmNDo4NjpiNzo1OTpjODoyNjo5Nzo1Njo1MzpiZToxYTozYTplZTpkOQogICAgU2lnbmF0dXJlIEFsZ29yaXRobTogc2hhMjU2V2l0aFJTQUVuY3J5cHRpb24KICAgICAgICBJc3N1ZXI6IENOPUNvdWNoYmFzZSBDQQogICAgICAgIFZhbGlkaXR5CiAgICAgICAgICAgIE5vdCBCZWZvcmU6IEZlYiAyMSAxNTo0OToxNSAyMDIwIEdNVAogICAgICAgICAgICBOb3QgQWZ0ZXIgOiBNYXkgMjYgMTU6NDk6MTUgMjAyMiBHTVQKICAgICAgICBTdWJqZWN0OiBDTj1jb3VjaGJhc2Utc2VydmVyCiAgICAgICAgU3ViamVjdCBQdWJsaWMgS2V5IEluZm86CiAgICAgICAgICAgIFB1YmxpYyBLZXkgQWxnb3JpdGhtOiByc2FFbmNyeXB0aW9uCiAgICAgICAgICAgICAgICBQdWJsaWMtS2V5OiAoMjA0OCBiaXQpCiAgICAgICAgICAgICAgICBNb2R1bHVzOgogICAgICAgICAgICAgICAgICAgIDAwOmRkOjlmOjgyOjQxOjdkOjY2OjM4Ojg3OjAwOmM0OjUxOmMyOmE1OjNlOgogICAgICAgICAgICAgICAgICAgIDkyOjlhOjRlOmI3OjlhOjM5OmE0OjYyOjIyOjZkOmU0OjlhOjQyOmUzOjQzOgogICAgICAgICAgICAgICAgICAgIDk5OjVhOmZlOmM5OjRmOjM2OjMwOjAwOjBhOjNmOjczOjRkOmRiOjYwOmNmOgogICAgICAgICAgICAgICAgICAgIDI3OmNmOjY3OjI5OjBhOjU2OjRjOmM5OjUwOjc5OjJmOjA5OmYwOjVjOmIxOgogICAgICAgICAgICAgICAgICAgIDBiOjIzOjY4OjBjOmVhOmE4OjI1OjY4OmEzOjZmOjY5OjkxOmVkOjg4OjA5OgogICAgICAgICAgICAgICAgICAgIDAwOjQyOmNmOmFlOjc1OmVhOmMzOjE3OmYyOjIyOmYyOjVkOjdmOmE2OmQxOgogICAgICAgICAgICAgICAgICAgIGU5OjRhOjA5OjU3OmM2Ojk2OmYwOmUzOjZlOmI3OmUxOjk3OmM4Ojc0OmFiOgogICAgICAgICAgICAgICAgICAgIDY2OjUxOjRmOjhiOjJmOjM4Ojk3OmNiOjk0OjQ5OmU2OjY2OmQwOjExOmQ2OgogICAgICAgICAgICAgICAgICAgIGJlOmQ1OmM3OmNlOjlkOjRmOjg0OjQ1OjU4OmUxOjM5OjUwOmZhOmNmOmRkOgogICAgICAgICAgICAgICAgICAgIGEzOmI1Ojk5OjRlOmU1Ojc4Ojg3OmY0OjMxOmQyOmU2OjcwOjE3OjM5OmQ4OgogICAgICAgICAgICAgICAgICAgIDA0OjVlOjY4OjIzOjRjOjQ4OjIwOmU2Ojc3OmNjOjRhOmYzOjE5OjkxOmY0OgogICAgICAgICAgICAgICAgICAgIDEzOjc3OjZjOjllOmRhOjk1OjU2OmQ0OmM2OmNlOjhiOjJmOmFmOjMwOjJjOgogICAgICAgICAgICAgICAgICAgIGJkOmYwOmExOmVhOjQ1OmViOmFkOmMwOmI3OmI3OmZkOmExOmI2Ojg5OjIxOgogICAgICAgICAgICAgICAgICAgIDg0OjMxOjMyOmIwOjUyOjE3OjAwOjIxOjMwOmRiOmIwOjNkOmNkOjRkOjg3OgogICAgICAgICAgICAgICAgICAgIGI3OjllOjhhOjBlOmYwOjA4OmNmOmNhOmZhOjEwOmMxOjQ5OjlhOjIxOmJiOgogICAgICAgICAgICAgICAgICAgIDAwOmZmOjlkOjk0OmEyOmRjOmE3OmZmOjgxOjcwOmQ4OjllOjk3Ojc0OjIxOgogICAgICAgICAgICAgICAgICAgIDZiOjRmOmE1OjIyOjQ2OmVjOmJlOjY4OjhmOmVkOjdkOjUwOmI5OjAzOjE3OgogICAgICAgICAgICAgICAgICAgIDM4OmRiCiAgICAgICAgICAgICAgICBFeHBvbmVudDogNjU1MzcgKDB4MTAwMDEpCiAgICAgICAgWDUwOXYzIGV4dGVuc2lvbnM6CiAgICAgICAgICAgIFg1MDl2MyBCYXNpYyBDb25zdHJhaW50czogCiAgICAgICAgICAgICAgICBDQTpGQUxTRQogICAgICAgICAgICBYNTA5djMgU3ViamVjdCBLZXkgSWRlbnRpZmllcjogCiAgICAgICAgICAgICAgICBDRDo4Qjo4RTo1Njo5RDpFNToyMjpDRDpBNDo4Mzo0NDoyODo0MzpDQTo4Qzo5MjpDMzpDNDo2QTo1OAogICAgICAgICAgICBYNTA5djMgQXV0aG9yaXR5IEtleSBJZGVudGlmaWVyOiAKICAgICAgICAgICAgICAgIGtleWlkOjU2OkEwOkI3OkE0Ojk3OkJFOkJDOkYzOkU3OkREOkUxOkYyOjBCOjVFOjM0OkUzOkU5OkFFOjg0Ojg0CiAgICAgICAgICAgICAgICBEaXJOYW1lOi9DTj1Db3VjaGJhc2UgQ0EKICAgICAgICAgICAgICAgIHNlcmlhbDpDMzpBQzo3RjpGQToxRjpBNTo1Mzo3OAoKICAgICAgICAgICAgWDUwOXYzIEV4dGVuZGVkIEtleSBVc2FnZTogCiAgICAgICAgICAgICAgICBUTFMgV2ViIFNlcnZlciBBdXRoZW50aWNhdGlvbgogICAgICAgICAgICBYNTA5djMgS2V5IFVzYWdlOiAKICAgICAgICAgICAgICAgIERpZ2l0YWwgU2lnbmF0dXJlLCBLZXkgRW5jaXBoZXJtZW50CiAgICAgICAgICAgIFg1MDl2MyBTdWJqZWN0IEFsdGVybmF0aXZlIE5hbWU6IAogICAgICAgICAgICAgICAgRE5TOiouY2ItZWtzLWNsdXN0ZXIuZW1hcnQuc3ZjLCBETlM6Ki5lbWFydC5zdmMsIEROUzoqLmNiLWVrcy1jbHVzdGVyLnNlZWFzdHVzLmNvbQogICAgU2lnbmF0dXJlIEFsZ29yaXRobTogc2hhMjU2V2l0aFJTQUVuY3J5cHRpb24KICAgICAgICAgOGQ6ODQ6OTM6ZTI6NDE6NjM6MGY6MTc6ODg6NGE6NmE6YjQ6OGQ6ZDk6Njk6YTI6MzY6MmI6CiAgICAgICAgIDZlOmUwOjBmOjcxOjc1OmYyOjA1OmRmOmQ4Ojg2OjdkOjBiOjliOjE3OjI4OmE0OjdkOjViOgogICAgICAgICA3Yzo2Nzo4OTozNTo2Mzo5MzoxNToxYToxZTpjZTpjMTphZjoxNToxNzo3ZTpjNzphZTozODoKICAgICAgICAgNDU6YjA6OGM6MjM6Y2M6NmU6MzY6YjM6NTY6NWM6YzU6Mzk6YzE6YTM6OTg6NDQ6N2M6MTc6CiAgICAgICAgIDc5OjZkOjhlOmZhOmUyOjRjOmNmOjAwOjFlOmZiOjMwOjI5OjE5OmM3OmY2OjRiOjk5OmMwOgogICAgICAgICAxOToyMDo1YTphYjoxMDpjMTo0OTo0Njo3ODpjMjoyOToxOToxZTo0NDo2ODphOTo3MToyZjoKICAgICAgICAgMGE6OGQ6ZTg6NzQ6ZTQ6OWE6Njk6MmE6MDI6YTU6MWI6NzQ6ZGU6Mzk6OGY6NjU6MTk6NDA6CiAgICAgICAgIGZkOjU0OmNmOjJlOjAxOmIyOmU3OjI1OmY0OmI3OmQ1OjVhOjdlOjQxOjdmOmY4Ojg4OjhkOgogICAgICAgICBjZjo1ZTo5OTphZjpmMTozYjphNjozYToxMzo5YTpkNTpmOTpmYzozMjo5ZTphNjo5Yzo5NDoKICAgICAgICAgMGE6MjE6Yjc6OTM6NWM6OTk6Nzk6Mzg6Mjc6ODM6NTU6MDA6ZjY6Yjg6ZmE6NWE6MzI6ZjM6CiAgICAgICAgIDZjOmFmOjI3OmZhOjAzOjg2OmMzOmQ5OjNhOmJiOjRlOjk4OmViOjBiOmE2Ojk4OjMzOjE3OgogICAgICAgICA5NTphMDpjZDoyYzo1ZToxMzoxMjoyZjozYzpkYTo5MzpjYjo2MjoxMDo1ZTo3Yjo4Mzo5ZToKICAgICAgICAgNDQ6YzI6ZjE6Y2M6M2I6MDM6YmM6NGY6Njc6NzU6NTk6YjQ6ZGY6Njk6N2E6ODk6Y2U6MmM6CiAgICAgICAgIDk5OjU0OmM4OmQwOjFhOjViOmI4OmRjOmIyOjlkOjQxOmRjOjYxOmU1OmNhOjRmOjQwOjAwOgogICAgICAgICA1ZTphNzoxYzoyNwotLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJRHFUQ0NBcEdnQXdJQkFnSVJBUDMwOUlhM1djZ21sMVpUdmhvNjd0a3dEUVlKS29aSWh2Y05BUUVMQlFBdwpGekVWTUJNR0ExVUVBd3dNUTI5MVkyaGlZWE5sSUVOQk1CNFhEVEl3TURJeU1URTFORGt4TlZvWERUSXlNRFV5Ck5qRTFORGt4TlZvd0d6RVpNQmNHQTFVRUF3d1FZMjkxWTJoaVlYTmxMWE5sY25abGNqQ0NBU0l3RFFZSktvWkkKaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFOMmZna0Y5WmppSEFNUlJ3cVUra3BwT3Q1bzVwR0lpYmVTYQpRdU5EbVZyK3lVODJNQUFLUDNOTjIyRFBKODluS1FwV1RNbFFlUzhKOEZ5eEN5Tm9ET3FvSldpamIybVI3WWdKCkFFTFByblhxd3hmeUl2SmRmNmJSNlVvSlY4YVc4T051dCtHWHlIU3JabEZQaXk4NGw4dVVTZVptMEJIV3Z0WEgKenAxUGhFVlk0VGxRK3MvZG83V1pUdVY0aC9ReDB1WndGem5ZQkY1b0kweElJT1ozekVyekdaSDBFM2RzbnRxVgpWdFRHem9zdnJ6QXN2ZkNoNmtYcnJjQzN0LzJodG9raGhERXlzRklYQUNFdzI3QTl6VTJIdDU2S0R2QUl6OHI2CkVNRkptaUc3QVArZGxLTGNwLytCY05pZWwzUWhhMCtsSWtic3ZtaVA3WDFRdVFNWE9Oc0NBd0VBQWFPQjZ6Q0IKNkRBSkJnTlZIUk1FQWpBQU1CMEdBMVVkRGdRV0JCVE5pNDVXbmVVaXphU0RSQ2hEeW95U3c4UnFXREJIQmdOVgpIU01FUURBK2dCUldvTGVrbDc2ODgrZmQ0ZklMWGpUajZhNkVoS0VicEJrd0Z6RVZNQk1HQTFVRUF3d01RMjkxClkyaGlZWE5sSUVOQmdna0F3NngvK2grbFUzZ3dFd1lEVlIwbEJBd3dDZ1lJS3dZQkJRVUhBd0V3Q3dZRFZSMFAKQkFRREFnV2dNRkVHQTFVZEVRUktNRWlDR2lvdVkySXRaV3R6TFdOc2RYTjBaWEl1WlcxaGNuUXVjM1pqZ2dzcQpMbVZ0WVhKMExuTjJZNElkS2k1allpMWxhM010WTJ4MWMzUmxjaTV6WldWaGMzUjFjeTVqYjIwd0RRWUpLb1pJCmh2Y05BUUVMQlFBRGdnRUJBSTJFaytKQll3OFhpRXBxdEkzWmFhSTJLMjdnRDNGMThnWGYySVo5QzVzWEtLUjkKVzN4bmlUVmpreFVhSHM3QnJ4VVhmc2V1T0VXd2pDUE1iamF6Vmx6Rk9jR2ptRVI4RjNsdGp2cmlUTThBSHZzdwpLUm5IOWt1WndCa2dXcXNRd1VsR2VNSXBHUjVFYUtseEx3cU42SFRrbW1rcUFxVWJkTjQ1ajJVWlFQMVV6eTRCCnN1Y2w5TGZWV241QmYvaUlqYzllbWEveE82WTZFNXJWK2Z3eW5xYWNsQW9odDVOY21YazRKNE5WQVBhNCtsb3kKODJ5dkovb0Roc1BaT3J0T21Pc0xwcGd6RjVXZ3pTeGVFeEl2UE5xVHkySVFYbnVEbmtUQzhjdzdBN3hQWjNWWgp0TjlwZW9uT0xKbFV5TkFhVzdqY3NwMUIzR0hseWs5QUFGNm5IQ2M9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    service:
      name: couchbase-operator-admission
      namespace: cb-eks
      path: /couchbaseclusters/mutate
  name: couchbase-operator-admission.cb-eks.svc
  rules:
  - apiGroups:
    - couchbase.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - couchbaseclusters

---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: couchbase-operator-admission
webhooks:
- clientConfig:
    caBundle: Q2VydGlmaWNhdGU6CiAgICBEYXRhOgogICAgICAgIFZlcnNpb246IDMgKDB4MikKICAgICAgICBTZXJpYWwgTnVtYmVyOgogICAgICAgICAgICBmZDpmNDpmNDo4NjpiNzo1OTpjODoyNjo5Nzo1Njo1MzpiZToxYTozYTplZTpkOQogICAgU2lnbmF0dXJlIEFsZ29yaXRobTogc2hhMjU2V2l0aFJTQUVuY3J5cHRpb24KICAgICAgICBJc3N1ZXI6IENOPUNvdWNoYmFzZSBDQQogICAgICAgIFZhbGlkaXR5CiAgICAgICAgICAgIE5vdCBCZWZvcmU6IEZlYiAyMSAxNTo0OToxNSAyMDIwIEdNVAogICAgICAgICAgICBOb3QgQWZ0ZXIgOiBNYXkgMjYgMTU6NDk6MTUgMjAyMiBHTVQKICAgICAgICBTdWJqZWN0OiBDTj1jb3VjaGJhc2Utc2VydmVyCiAgICAgICAgU3ViamVjdCBQdWJsaWMgS2V5IEluZm86CiAgICAgICAgICAgIFB1YmxpYyBLZXkgQWxnb3JpdGhtOiByc2FFbmNyeXB0aW9uCiAgICAgICAgICAgICAgICBQdWJsaWMtS2V5OiAoMjA0OCBiaXQpCiAgICAgICAgICAgICAgICBNb2R1bHVzOgogICAgICAgICAgICAgICAgICAgIDAwOmRkOjlmOjgyOjQxOjdkOjY2OjM4Ojg3OjAwOmM0OjUxOmMyOmE1OjNlOgogICAgICAgICAgICAgICAgICAgIDkyOjlhOjRlOmI3OjlhOjM5OmE0OjYyOjIyOjZkOmU0OjlhOjQyOmUzOjQzOgogICAgICAgICAgICAgICAgICAgIDk5OjVhOmZlOmM5OjRmOjM2OjMwOjAwOjBhOjNmOjczOjRkOmRiOjYwOmNmOgogICAgICAgICAgICAgICAgICAgIDI3OmNmOjY3OjI5OjBhOjU2OjRjOmM5OjUwOjc5OjJmOjA5OmYwOjVjOmIxOgogICAgICAgICAgICAgICAgICAgIDBiOjIzOjY4OjBjOmVhOmE4OjI1OjY4OmEzOjZmOjY5OjkxOmVkOjg4OjA5OgogICAgICAgICAgICAgICAgICAgIDAwOjQyOmNmOmFlOjc1OmVhOmMzOjE3OmYyOjIyOmYyOjVkOjdmOmE2OmQxOgogICAgICAgICAgICAgICAgICAgIGU5OjRhOjA5OjU3OmM2Ojk2OmYwOmUzOjZlOmI3OmUxOjk3OmM4Ojc0OmFiOgogICAgICAgICAgICAgICAgICAgIDY2OjUxOjRmOjhiOjJmOjM4Ojk3OmNiOjk0OjQ5OmU2OjY2OmQwOjExOmQ2OgogICAgICAgICAgICAgICAgICAgIGJlOmQ1OmM3OmNlOjlkOjRmOjg0OjQ1OjU4OmUxOjM5OjUwOmZhOmNmOmRkOgogICAgICAgICAgICAgICAgICAgIGEzOmI1Ojk5OjRlOmU1Ojc4Ojg3OmY0OjMxOmQyOmU2OjcwOjE3OjM5OmQ4OgogICAgICAgICAgICAgICAgICAgIDA0OjVlOjY4OjIzOjRjOjQ4OjIwOmU2Ojc3OmNjOjRhOmYzOjE5OjkxOmY0OgogICAgICAgICAgICAgICAgICAgIDEzOjc3OjZjOjllOmRhOjk1OjU2OmQ0OmM2OmNlOjhiOjJmOmFmOjMwOjJjOgogICAgICAgICAgICAgICAgICAgIGJkOmYwOmExOmVhOjQ1OmViOmFkOmMwOmI3OmI3OmZkOmExOmI2Ojg5OjIxOgogICAgICAgICAgICAgICAgICAgIDg0OjMxOjMyOmIwOjUyOjE3OjAwOjIxOjMwOmRiOmIwOjNkOmNkOjRkOjg3OgogICAgICAgICAgICAgICAgICAgIGI3OjllOjhhOjBlOmYwOjA4OmNmOmNhOmZhOjEwOmMxOjQ5OjlhOjIxOmJiOgogICAgICAgICAgICAgICAgICAgIDAwOmZmOjlkOjk0OmEyOmRjOmE3OmZmOjgxOjcwOmQ4OjllOjk3Ojc0OjIxOgogICAgICAgICAgICAgICAgICAgIDZiOjRmOmE1OjIyOjQ2OmVjOmJlOjY4OjhmOmVkOjdkOjUwOmI5OjAzOjE3OgogICAgICAgICAgICAgICAgICAgIDM4OmRiCiAgICAgICAgICAgICAgICBFeHBvbmVudDogNjU1MzcgKDB4MTAwMDEpCiAgICAgICAgWDUwOXYzIGV4dGVuc2lvbnM6CiAgICAgICAgICAgIFg1MDl2MyBCYXNpYyBDb25zdHJhaW50czogCiAgICAgICAgICAgICAgICBDQTpGQUxTRQogICAgICAgICAgICBYNTA5djMgU3ViamVjdCBLZXkgSWRlbnRpZmllcjogCiAgICAgICAgICAgICAgICBDRDo4Qjo4RTo1Njo5RDpFNToyMjpDRDpBNDo4Mzo0NDoyODo0MzpDQTo4Qzo5MjpDMzpDNDo2QTo1OAogICAgICAgICAgICBYNTA5djMgQXV0aG9yaXR5IEtleSBJZGVudGlmaWVyOiAKICAgICAgICAgICAgICAgIGtleWlkOjU2OkEwOkI3OkE0Ojk3OkJFOkJDOkYzOkU3OkREOkUxOkYyOjBCOjVFOjM0OkUzOkU5OkFFOjg0Ojg0CiAgICAgICAgICAgICAgICBEaXJOYW1lOi9DTj1Db3VjaGJhc2UgQ0EKICAgICAgICAgICAgICAgIHNlcmlhbDpDMzpBQzo3RjpGQToxRjpBNTo1Mzo3OAoKICAgICAgICAgICAgWDUwOXYzIEV4dGVuZGVkIEtleSBVc2FnZTogCiAgICAgICAgICAgICAgICBUTFMgV2ViIFNlcnZlciBBdXRoZW50aWNhdGlvbgogICAgICAgICAgICBYNTA5djMgS2V5IFVzYWdlOiAKICAgICAgICAgICAgICAgIERpZ2l0YWwgU2lnbmF0dXJlLCBLZXkgRW5jaXBoZXJtZW50CiAgICAgICAgICAgIFg1MDl2MyBTdWJqZWN0IEFsdGVybmF0aXZlIE5hbWU6IAogICAgICAgICAgICAgICAgRE5TOiouY2ItZWtzLWNsdXN0ZXIuZW1hcnQuc3ZjLCBETlM6Ki5lbWFydC5zdmMsIEROUzoqLmNiLWVrcy1jbHVzdGVyLnNlZWFzdHVzLmNvbQogICAgU2lnbmF0dXJlIEFsZ29yaXRobTogc2hhMjU2V2l0aFJTQUVuY3J5cHRpb24KICAgICAgICAgOGQ6ODQ6OTM6ZTI6NDE6NjM6MGY6MTc6ODg6NGE6NmE6YjQ6OGQ6ZDk6Njk6YTI6MzY6MmI6CiAgICAgICAgIDZlOmUwOjBmOjcxOjc1OmYyOjA1OmRmOmQ4Ojg2OjdkOjBiOjliOjE3OjI4OmE0OjdkOjViOgogICAgICAgICA3Yzo2Nzo4OTozNTo2Mzo5MzoxNToxYToxZTpjZTpjMTphZjoxNToxNzo3ZTpjNzphZTozODoKICAgICAgICAgNDU6YjA6OGM6MjM6Y2M6NmU6MzY6YjM6NTY6NWM6YzU6Mzk6YzE6YTM6OTg6NDQ6N2M6MTc6CiAgICAgICAgIDc5OjZkOjhlOmZhOmUyOjRjOmNmOjAwOjFlOmZiOjMwOjI5OjE5OmM3OmY2OjRiOjk5OmMwOgogICAgICAgICAxOToyMDo1YTphYjoxMDpjMTo0OTo0Njo3ODpjMjoyOToxOToxZTo0NDo2ODphOTo3MToyZjoKICAgICAgICAgMGE6OGQ6ZTg6NzQ6ZTQ6OWE6Njk6MmE6MDI6YTU6MWI6NzQ6ZGU6Mzk6OGY6NjU6MTk6NDA6CiAgICAgICAgIGZkOjU0OmNmOjJlOjAxOmIyOmU3OjI1OmY0OmI3OmQ1OjVhOjdlOjQxOjdmOmY4Ojg4OjhkOgogICAgICAgICBjZjo1ZTo5OTphZjpmMTozYjphNjozYToxMzo5YTpkNTpmOTpmYzozMjo5ZTphNjo5Yzo5NDoKICAgICAgICAgMGE6MjE6Yjc6OTM6NWM6OTk6Nzk6Mzg6Mjc6ODM6NTU6MDA6ZjY6Yjg6ZmE6NWE6MzI6ZjM6CiAgICAgICAgIDZjOmFmOjI3OmZhOjAzOjg2OmMzOmQ5OjNhOmJiOjRlOjk4OmViOjBiOmE2Ojk4OjMzOjE3OgogICAgICAgICA5NTphMDpjZDoyYzo1ZToxMzoxMjoyZjozYzpkYTo5MzpjYjo2MjoxMDo1ZTo3Yjo4Mzo5ZToKICAgICAgICAgNDQ6YzI6ZjE6Y2M6M2I6MDM6YmM6NGY6Njc6NzU6NTk6YjQ6ZGY6Njk6N2E6ODk6Y2U6MmM6CiAgICAgICAgIDk5OjU0OmM4OmQwOjFhOjViOmI4OmRjOmIyOjlkOjQxOmRjOjYxOmU1OmNhOjRmOjQwOjAwOgogICAgICAgICA1ZTphNzoxYzoyNwotLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJRHFUQ0NBcEdnQXdJQkFnSVJBUDMwOUlhM1djZ21sMVpUdmhvNjd0a3dEUVlKS29aSWh2Y05BUUVMQlFBdwpGekVWTUJNR0ExVUVBd3dNUTI5MVkyaGlZWE5sSUVOQk1CNFhEVEl3TURJeU1URTFORGt4TlZvWERUSXlNRFV5Ck5qRTFORGt4TlZvd0d6RVpNQmNHQTFVRUF3d1FZMjkxWTJoaVlYTmxMWE5sY25abGNqQ0NBU0l3RFFZSktvWkkKaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFOMmZna0Y5WmppSEFNUlJ3cVUra3BwT3Q1bzVwR0lpYmVTYQpRdU5EbVZyK3lVODJNQUFLUDNOTjIyRFBKODluS1FwV1RNbFFlUzhKOEZ5eEN5Tm9ET3FvSldpamIybVI3WWdKCkFFTFByblhxd3hmeUl2SmRmNmJSNlVvSlY4YVc4T051dCtHWHlIU3JabEZQaXk4NGw4dVVTZVptMEJIV3Z0WEgKenAxUGhFVlk0VGxRK3MvZG83V1pUdVY0aC9ReDB1WndGem5ZQkY1b0kweElJT1ozekVyekdaSDBFM2RzbnRxVgpWdFRHem9zdnJ6QXN2ZkNoNmtYcnJjQzN0LzJodG9raGhERXlzRklYQUNFdzI3QTl6VTJIdDU2S0R2QUl6OHI2CkVNRkptaUc3QVArZGxLTGNwLytCY05pZWwzUWhhMCtsSWtic3ZtaVA3WDFRdVFNWE9Oc0NBd0VBQWFPQjZ6Q0IKNkRBSkJnTlZIUk1FQWpBQU1CMEdBMVVkRGdRV0JCVE5pNDVXbmVVaXphU0RSQ2hEeW95U3c4UnFXREJIQmdOVgpIU01FUURBK2dCUldvTGVrbDc2ODgrZmQ0ZklMWGpUajZhNkVoS0VicEJrd0Z6RVZNQk1HQTFVRUF3d01RMjkxClkyaGlZWE5sSUVOQmdna0F3NngvK2grbFUzZ3dFd1lEVlIwbEJBd3dDZ1lJS3dZQkJRVUhBd0V3Q3dZRFZSMFAKQkFRREFnV2dNRkVHQTFVZEVRUktNRWlDR2lvdVkySXRaV3R6TFdOc2RYTjBaWEl1WlcxaGNuUXVjM1pqZ2dzcQpMbVZ0WVhKMExuTjJZNElkS2k1allpMWxhM010WTJ4MWMzUmxjaTV6WldWaGMzUjFjeTVqYjIwd0RRWUpLb1pJCmh2Y05BUUVMQlFBRGdnRUJBSTJFaytKQll3OFhpRXBxdEkzWmFhSTJLMjdnRDNGMThnWGYySVo5QzVzWEtLUjkKVzN4bmlUVmpreFVhSHM3QnJ4VVhmc2V1T0VXd2pDUE1iamF6Vmx6Rk9jR2ptRVI4RjNsdGp2cmlUTThBSHZzdwpLUm5IOWt1WndCa2dXcXNRd1VsR2VNSXBHUjVFYUtseEx3cU42SFRrbW1rcUFxVWJkTjQ1ajJVWlFQMVV6eTRCCnN1Y2w5TGZWV241QmYvaUlqYzllbWEveE82WTZFNXJWK2Z3eW5xYWNsQW9odDVOY21YazRKNE5WQVBhNCtsb3kKODJ5dkovb0Roc1BaT3J0T21Pc0xwcGd6RjVXZ3pTeGVFeEl2UE5xVHkySVFYbnVEbmtUQzhjdzdBN3hQWjNWWgp0TjlwZW9uT0xKbFV5TkFhVzdqY3NwMUIzR0hseWs5QUFGNm5IQ2M9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    service:
      name: couchbase-operator-admission
      namespace: cb-eks
      path: /couchbaseclusters/validate
  name: couchbase-operator-admission.cb-eks.svc
  rules:
  - apiGroups:
    - couchbase.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - couchbaseclusters

