metadata:
  creationTimestamp: "2020-02-20T15:44:10Z"
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
  name: compose-stack-admin
  resourceVersion: "534"
  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterroles/compose-stack-admin
  uid: 2bacf647-0106-42ec-8b78-57e975046630
rules:
- apiGroups:
  - compose.docker.com
  resources:
  - stacks
  - stacks/scale
  - stacks/log
  - stacks/composeFile
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - compose.docker.com
  resources:
  - stacks/owner
  verbs:
  - get
