metadata:
  creationTimestamp: "2020-02-20T15:44:09Z"
  labels:
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
  name: compose-stack-edit
  resourceVersion: "528"
  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterroles/compose-stack-edit
  uid: 4be2a273-e813-4f5f-b9c3-93406eec9834
rules:
- apiGroups:
  - compose.docker.com
  resources:
  - stacks
  - stacks/scale
  - stacks/log
  - stacks/composeFile
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
