metadata:
  creationTimestamp: "2020-02-20T15:44:09Z"
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
  name: compose-stack-view
  resourceVersion: "522"
  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterroles/compose-stack-view
  uid: 72fd2223-07df-45c3-b99e-467ce57ab5ba
rules:
- apiGroups:
  - compose.docker.com
  resources:
  - stacks
  - stacks/scale
  - stacks/log
  - stacks/composeFile
  verbs:
  - get
  - list
  - watch
